In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

train=pd.read_csv('classification_train.csv')

x_train=train.drop(['Unnamed: 0','label'],axis=1)
y_train=train['label']
x_train.to_numpy     #turning the dataframes into numpy arrays
y_train.to_numpy
y1 = np.zeros([x_train.shape[0], len(y_train.unique())])
for i in range(x_train.shape[0]):     #for each different class and different obs ,turning the obs at that point to 1
    y1[i, y_train[i]] = 1

def Logistic_Regression(x,y,alpha,iterations):
    m, n = x.shape
  

    w=np.zeros((n,y.shape[1]))
    b=np.zeros((1,y.shape[1]))
    j_his=[]
  
  
    for k in range(iterations):
        z = np.dot(x,w)+b
      
        y_pred = 1/(1+np.exp(-z))
      #print(y_pred)
        cost =  -(1/m)*np.sum((y*np.log(y_pred) + (1-y)*np.log(1-y_pred)))
        dj_dw = (1/m) * (np.dot(x.T, (y_pred - y)))
        dj_db = (1/m) * (np.sum(y_pred-y, axis=0, keepdims=True))
        j_his.append(cost)
        if (i>0):  
            if (cost>j_his[k-1]):
                w_actual=w
                b_actual=b
                print(f'w_actual:{w_actual},b_actual:{b_actual},i:{k}')
                break
            elif(k==3999):
                w_actual=w
                b_actual=b
                print(f'w_actual:{w_actual},b_actual:{b_actual},i:{k}')
                break
            else:
                pass
            
        w -= (alpha)*(dj_dw)
        b -= (alpha)*(dj_db)

        j_his.append(cost)

        if k%100==0:
            print(cost)
        
    return w_actual, b_actual, j_his

iterations=4000
alpha=0.000001
w, b, cost = Logistic_Regression(x_train, y1, alpha, iterations)

6.931471805599448
1.6231612319501019
1.4270320182416054
1.3312848753135804
1.2712498414927018
1.2290869478532773
1.1973737546927075
1.1723775789285886
1.151992465418899
1.134931087148704
1.120357822455454
1.1077041875657343
1.0965685451092038
1.0866581749266744
1.0777541067615695
1.069688869241617
1.0623319101879682
1.0555797528804245
1.0493491749817692
1.0435723732163427
1.0381934661268086
1.0331659189630802
1.0284506169175498
1.0240144024854985
1.0198289505178806
1.0158698926275862
1.0121161282139484
1.008549276885728
1.0051532392404021
1.0019138415505175
0.9988185460549126
0.9958562130059886
0.9930169038886653
0.9902917176459828
0.9876726535576642
0.9851524957871983
0.9827247156573377
0.9803833885171953
0.9781231226869033
0.9759389984522595
w_actual:[[ 1.69733388e-07 -8.94765544e-09 -3.43425728e-07 ... -1.17686709e-09
   3.35491808e-07 -2.27887603e-09]
 [ 1.35190833e-06 -5.93303900e-08 -9.38278344e-07 ... -2.67300442e-08
   5.22146542e-07  4.32960681e-07]
 [ 1.10982433e-05 -1.26078158e-06 -6.68472093e-07 ... -3.17621061e-07
  -2.62566951e-05 -4.40458902e-07]
 ...
 [-1.43273612e-04 -1.35490055e-05  3.99437736e-04 ... -5.22454159e-05
  -2.19022402e-04 -2.59661458e-05]
 [-6.18279996e-05 -1.69433701e-05  1.39403331e-04 ... -2.59964403e-05
  -1.19316635e-04 -6.94393592e-06]
 [-1.44525101e-06 -5.57848579e-07  4.14953741e-05 ... -7.78840574e-07
  -2.44914330e-05  4.81769733e-06]],b_actual:[[-2.67881165e-05 -2.10306740e-05 -4.67868301e-05 -2.53897268e-05
  -7.07912295e-05  3.64522529e-05 -3.71245321e-05 -2.63514987e-05
  -5.32532498e-05 -5.33648804e-05]],i:3999

In [17]:
theta1 = pd.DataFrame(w)
theta1.iloc[:,1].shape

(784,)

In [18]:
def sigmoid(x,y,w,b):
    return 1 / (1 + np.exp(-(np.dot(theta, X.T)+b)))

In [19]:
x=np.array(x_train)

In [20]:
lis=[]
for i in range(len(x_train)):
    
    y_pred=1/(1+np.exp(-(np.dot(w.T,x[i])+b)))
    y_pred1=y_pred.reshape((10))
    lis.append(y_pred1)

In [21]:
k=pd.DataFrame(lis)
k

,0,1,2,3,4,5,6,7,8,9
0,0.000028,3.468387e-06,0.000020,8.921988e-06,0.000022,2.600732e-01,0.000053,1.624677e-01,0.001368,4.597468e-03
1,0.001178,3.183229e-05,0.011857,2.952443e-04,0.573994,4.065886e-06,0.090682,2.871838e-09,0.001814,1.932742e-08
2,0.067635,6.190834e-01,0.019545,1.776868e-01,0.042952,3.904098e-06,0.050127,3.434556e-04,0.000340,5.894019e-05
3,0.000043,1.049600e-07,0.003847,6.754819e-08,0.000384,1.799087e-05,0.002141,1.394665e-08,0.990731,1.292406e-06
4,0.001023,5.424407e-04,0.413294,4.417692e-04,0.313543,8.742460e-06,0.212758,7.912144e-08,0.000429,6.894807e-07
...,...,...,...,...,...,...,...,...,...,...
29995,0.030674,1.275573e-04,0.191035,4.921611e-01,0.029236,3.675271e-07,0.018706,1.549945e-09,0.000031,1.007326e-09
29996,0.000939,1.322837e-03,0.128678,2.143157e-04,0.734344,7.434444e-06,0.062210,2.053572e-08,0.001572,1.833412e-07
29997,0.000302,8.865158e-05,0.000020,2.057255e-04,0.000009,3.510484e-02,0.000066,2.309134e-02,0.000029,9.674212e-01
29998,0.028728,3.313745e-02,0.494540,1.651985e-01,0.579752,3.220341e-04,0.414825,3.419365e-05,0.000906,2.444031e-03
29999,0.759517,3.316436e-04,0.010314,4.468975e-04,0.000015,5.246421e-08,0.007733,9.745403e-08,0.000001,1.146016e-05

In [22]:
count=0
for i in range(10):
    for j in range(30000):
        if y1[j,i]==1 and k.iloc[j,i]>0.5:
            count+=1
        else:
            pass
print(count/k.shape[0])

0.7772

In [6]:
#df=pd.DataFrame(np.zeros((30000,10)))
#df

In [5]:
#

In [4]:
#y_train[1]